del /q "%USERPROFILE%\Documents\Elder Scrolls Online\live\AddOns\CyrodiilTracker\*.*"
copy *.lua "%USERPROFILE%\Documents\Elder Scrolls Online\live\AddOns\CyrodiilTracker\"
copy *.txt "%USERPROFILE%\Documents\Elder Scrolls Online\live\AddOns\CyrodiilTracker\"
copy *.xml "%USERPROFILE%\Documents\Elder Scrolls Online\live\AddOns\CyrodiilTracker\"
copy *.ttf "%USERPROFILE%\Documents\Elder Scrolls Online\live\AddOns\CyrodiilTracker\"